# Generated by Django 6.1.1 on 2026-09-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.CharField(max_length=300)),
                ('category', models.CharField(db_index=True, max_length=40)),
                ('price', models.PositiveIntegerField()),
                ('original_price', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_new', models.BooleanField(default=False)),
                ('is_sale', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=60)),
                ('colors', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('story', models.TextField(blank=True)),
                ('details', models.JSONField(default=list)),
                ('specs', models.JSONField(default=dict)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('reviews', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
    ]
